### ISSUE TITLE
40th webpage

### ISSUE THREAD

**Issue by pyarmak** [cfms-website/cfms-website.github.io#1]
### Create a 40th celebration webpage

Ideally, it would be a copy of the 40th logo (or just “1977-2017”) somewhere on that home page, which would link to info on the 40th celebrations.

> For the moment you can put a placeholder “details to come”.

**Comment by AntheaLafreniere** [comment]
I've e-mailed 40th logo photo files to you!

**Comment by pyarmak** [comment]
Created a promotional banner on the front page that currently links nowhere. Will update when there's content to put on the page.
