### ISSUE TITLE
English vs. French Webpages Transitions

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#10]
Would it be possible that when you click between En/Fr at the top, that it switches to the French version of that page instead of navigating back to the home screen?

Thanks!
- Evan Mah

Re: Lucy Lou

**Comment by pyarmak** [comment]
This was more involved than I thought but I got it done!
**The language select will not re-direct to the home page anymore but rather will reload the current page in the selected language.**

Finished in https://github.com/cfms-website/cfms-website.github.io/commit/64009773e4cc93b7d0c12006e51fa3c21e47e7ce.

**Comment by erm619** [comment]
It looks great and works great! Just tried it out. 

Thanks!

**Comment by erm619** [comment]
Hey @pyarmak - I don't know if it's my browser, but I am not able to use the Fr button to switch to the French side at all. Even from the home page.

**Comment by pyarmak** [comment]
@erm619 I just tried and it worked. That doesn't guarantee that nothing strange is happening so I'll take a look later tonight.

**Comment by pyarmak** [comment]
See: https://github.com/cfms-website/cfms-website.github.io/commit/2d8995af1eea19f562228bec3536a0204a8d1f8e.
Hit me up if you have questions.
