### ISSUE TITLE
Request for Humans of Medicine blog

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#11]
As previously discussed, the communications team is carrying out the Humans of Medicine campaign to share the stories and experiences of medical students.
It is based on the "Humans of New York" theme.

We are hoping to have these images and stories shared on the CFMS website, on a blog post style page. 

If you have any ideas on the structure, or need ideas, please let me know! 
Thanks,
Evan Mah

Re: Usman Khan

**Comment by pyarmak** [comment]
This was Stephen's project.

@Stephen please post an update in this issue thread (and assign yourself).

Re: Stephen Leung

**Comment by sleun090** [comment]
Hi guys, 

 Yes this is assigned to me.  Will keep you posted after LMCC (thursday)!

**Comment by Threatsignal** [comment]
@VP-Communications
see #104
