### ISSUE TITLE
Addition of President-Elect Profile

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#12]
Could you please add space for a new profile on both the English and French Who We Are > Executives and Officers, please?

Image: _to come at a later date_
**Title**: President-Elect
**Name**: Henry Annan
**Description**: Henry serves as President-Elect from April to September until his installation as President at AGM .  In this role, he will work alongside the CFMS President to understand the responsibilities of President, to develop his strategic vision for the organization, and to begin to connect with our partners and stakeholders. 
_note: I will get a French translation for the french page_
**Email**: presidentelect@cfms.org

Thank you,
Evan Mah

Re: Usman Khan

**Comment by erm619** [comment]
![dsc_5937](https://cloud.githubusercontent.com/assets/28280012/25676543/9a967366-2fff-11e7-8864-8c1e10c71e40.jpg)

**Comment by sleun090** [comment]
Added the english side.  Awaiting the french side to be translated.

**Comment by erm619** [comment]
@sleun090 Please find the French version below:

Président élu 

Henry sera Président-élu durant la période du avril au septembre, jusqu'à son investiture en tant que président à l’Assemblée Générale Annuelle (AGM). Dans ce rôle, il travaillera avec le président de la FEMC afin de mieux comprendre les responsabilités du président, développer sa vision stratégique de l'organisation et commencer à communiquer avec nos partenaires et nos membres.

Thank you,
Evan
