### ISSUE TITLE
Clean up website root

### ISSUE THREAD

**Issue by pyarmak** [cfms-website/cfms-website.github.io#13]
There are way too many loose files found in the website root. 
Hunt down where they are linked to from the website and move them to appropriate folders.

**Comment by sleun090** [comment]
This might have something to do with allowing the execs to post the files using the class=editable. I think that the default action dumps it to the root.  Is there a way to change that ?

**Comment by erm619** [comment]
Is this something that I can help with, with re-organizing where files are stored? 
Not really capable of helping with the coding, but if I can help in other ways, please let me know!

**Comment by pyarmak** [comment]
I believe the execs can choose where to put the files, the default is the website root but they can change it. Correct me if I'm wrong of course. 

I'd be very happy if we can get someone to retroactively organize the files. 

Not a huge priority—just me being a bit OCD is all.

**Comment by Threatsignal** [comment]
see #116
