### ISSUE TITLE
CFMS Interview Database

### ISSUE THREAD

**Issue by starz2018** [cfms-website/cfms-website.github.io#131]
The database isn't working for the interview resource. Has it been taken down?

**Comment by starz2018** [comment]
Whenever i click a school, or speciality /both, it doesn't load anything

**Comment by Threatsignal** [comment]
Hi there @starz2018 
The Database works. There is a button that appears once Both a school and specialty have been selected. However, it's just not that intuitive that a button should appear at the moment. I had gotten too caught up in the functionality of it and forgot about User Experience. Thank you for your input. I'll update and fix it in a couple days when I get back from Holidays so that it is more intuitive.

**Comment by starz2018** [comment]
Thanks! So when i click for example "UBC" and "family medicine", the table is still empty. I'm allowed to ADD my own, but not able to see anything. Is it supposed to be like this? Sorry I've never used it before so I'm not sure what it's supposed to look like. 

Thanks 
Manpreet

**Comment by Threatsignal** [comment]
@starz2018 At the moment, When you select a school and specialty a button named "Add Entry" will appear. If you click that a drop-down form will appear. Once you fill out the forms minimally required values, it will add it to the database and your entry should appear in the Database. 

The reason it says there are no values is that at the moment for that particular school/specialty combination, there are no interviews added.

To add an entry, for now, Select a school, then select a specialty. Once a school and specialty have been selected, a button named "Add Entry" will appear on the page, click that button. Once the button is clicked, a form will drop down, Fill out the form with the required attributes ( I believe the only required attribute is overall Impression). Once you have filled out the form to your liking, click Add and it will be added to the database for that particular school/specialty. If needed you may edit or delete entries that you have posted.

Let me know if there are any further issues and anything else confusing about the Process, your input is appreciated as It helps me improve the User Experience for others in the future, Thanks for your time, Manpreet.

-Justin
