### ISSUE TITLE
Problem with Page Design

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#14]
The French version of the "Why Create An Account" at [https://www.cfms.org/fr/new-account.html](url) does not match that of the English version. 

When you click on "Create a New Account" after pressing 'login' on the French webpage, you get directed to the English version instead of the French.

**Comment by sleun090** [comment]
I've mirrored the english side to correct for the errors that were showing up but in fact there's no french side translation for this page.  We need a translation for this page.
