### ISSUE TITLE
Student Affairs Menu

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#17]
Can you please update the Menu For /Fr/What-We-Do/Student-Affairs to

Affaires étudiantes _(student affairs)_
Aperçu _(overview)_
Notre conseil _(our team)_
Ressources _(Resources)_
Bien-être _(Wellness)_
Rabais étudiants _(Student discount)_

**Comment by pyarmak** [comment]
Done in https://github.com/cfms-website/cfms-website.github.io/commit/e8149c2963aba66a56c124fe024056a2e9dbf9ab.
