### ISSUE TITLE
Education Menu 

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#18]
Could you please update the menu under /Fr/What-We-Do/Education to the following:

Éducation _(education)_
Aperçu _(overview)_
Notre conseil _(our team)_
Plaidoirie scolaire _(education advocacy)_
Président national de recherche _(national research chair)_

Ressources _(resources)_
Guide pour le jumelage en résidence _(residency matchbook)_
Trousse-à-outils pour cliniques dirigées par étudiants _(student run clinic toolkit)_
Ressources préparatoires pour LCMC _(LMCC preparation resources)_

Thanks,
Evan

**Comment by pyarmak** [comment]
Duplicate of #9. 
One thread per issue please and thank you 👍

**Comment by erm619** [comment]
You'd think I would have been able to notice that after posting them ... sorry man!
