### ISSUE TITLE
Advocacy Menu

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#19]
I think this was the one I meant to do instead of Education twice ... 

Update the /Fr/What-We-Do/Advocacy menu to:

Plaidoirie _(advocacy)_
Aperçu _(overview)_
Notre conseil _(our team)_

Ressources
Journée de plaidoirie _(lobby day)_
Exposés de position _(position papers)_
Trousse-à-outils pour plaidoirie _(toolkit)_

Thanks,
Evan

**Comment by pyarmak** [comment]
Done in https://github.com/cfms-website/cfms-website.github.io/commit/946347ac77c91b538ad123958bfcc86c7a913a42.
Woohoo daily streak is alive!
