### ISSUE TITLE
Student Affairs Resources

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#20]
I think this is new, but I am pretty sure that under What-We-Do/Student-Affairs, there were resources listed on the sidebar menu (Wellness, Leadership Awards, Student Discounts). But for both the En and Fr versions, there is nothing listed on the sidebar menu.

Not sure if this is intentional, but just something I noticed.

**Comment by pyarmak** [comment]
My bad! Made a typo.
Resolved in https://github.com/cfms-website/cfms-website.github.io/commit/7b266cd0035f6c684f19855b50ccd544ff457bc1.
