### ISSUE TITLE
Site Map

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#21]
There are a bunch of broken links, primarily under Education, and I am not sure what pages they are supposed to go to.

The Login Options (Create a new account, Why become a member) both don't link to anywhere.

Also, not all of the meetings are currently posted on the site map, the most recent one listed is AGM 2015.

**Comment by pyarmak** [comment]
Ideally, we want to dynamically generate the sitemap.

**Comment by Threatsignal** [comment]
Done, See #129
