### ISSUE TITLE
Create & link to a GitHub website issue tracker guide

### ISSUE THREAD

**Issue by pyarmak** [cfms-website/cfms-website.github.io#22]
Create a guide for the general membership (or anyone really) describing the procedure of posting a website issue on the website's GitHub repository issue tracker.

Once that's done, link to this guide, and to the issue tracker (probably on news ribbon) so that general members can participate (collaborate!) on website changes.

**Transparency, communication, and general membership involvement, oh my!**

> Don't mind my crazy ramblings; I pep talk myself up!

**Comment by erm619** [comment]
@pyarmak you can assign this to me! I'd be happy to start the work on this

**Comment by erm619** [comment]
@pyarmak - how does this look for a start? 

[Submitting Ticket for CFMS Website.docx](https://github.com/cfms-website/cfms-website.github.io/files/1000120/Submitting.Ticket.for.CFMS.Website.docx)

**Comment by erm619** [comment]
@pyarmak Can this be marked as done?
