### ISSUE TITLE
Advocacy References

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#23]
So similar to #20 , the Resources that were previously listed on the sidebar of the Advocacy pages, have disappeared. 

Thanks,
Evan

**Comment by pyarmak** [comment]
Ugh, my bad... Again. Resolved in https://github.com/cfms-website/cfms-website.github.io/commit/e1ee3eb1cb1fb1ec050d64654749c251c0245543.
This is what I get for being lazy, copy & pasting, then not testing and committing. 

Thanks for keeping me honest @erm619 Evan!
