### ISSUE TITLE
Posting News - English Versus French

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#24]
Did we come up with a way of separating the postings that are English and French?

I recall that we wanted to keep them separated, instead of having both languages on the same one.

**Comment by pyarmak** [comment]
@sleun090 This one should be solvable in a similar way to the humans of medicine issue. E.g. creating another jekyll collection.

**Comment by pyarmak** [comment]
See: https://github.com/cfms-website/cfms-website.github.io/commit/2d8995af1eea19f562228bec3536a0204a8d1f8e.
Hit me up if you have questions.

**Comment by erm619** [comment]
Wow! Looks awesome.

I don't know if someone has the original, but is there a way to update the Dropbox explanation about how to add files, to include this as well? 

[https://paper.dropbox.com/doc/Submitting-articles-to-the-CFMS-Website-rZVO8QmkfugMbMDCyMExs](url)

**Comment by pyarmak** [comment]
@erm619 sigh, I wish I could make documentation as beautiful as Kevan's...
Do also note that the dates and file names of the french and english versions must match in order for language switching to work properly.

**Comment by erm619** [comment]
@pyarmak - when you mention that the dates and file names must match, does that mean that to file names (ie the title of the documents) needs to be in English for the French site as well?

**Comment by erm619** [comment]
Also, @pyarmak - what is your intended use of the "Categories" description under the menu? Were you thinking - "Media", "Education", "Applications". - That sort of thing? Just want to make sure I have an adequate description of what it should be used for!

**Comment by pyarmak** [comment]
Reopening until I can get some actual documentation out on this feature.
