### ISSUE TITLE
MDFM Updates

### ISSUE THREAD

**Issue by AntheaLafreniere** [cfms-website/cfms-website.github.io#3]
Travel Awards Section:

- [ ] Content needs to be updated to speak a general overview, and if possible, dates that the “call for applications” will go out each year. I have provided some suggested copy attached that would allow you to not have to update this page as frequently – see attached.
- [ ] As discussed, moving forward we would like to see the live application housed here as well with the updated application form (Only required when call for applications is live)
- [ ] The Travel funding section of the SGM page does not mention MD at all – if we can please add MD in here somewhere

 
Leadership Awards Section

- [x] Remove Leadership Awards banner on the main CFMS page – out of date
- [x] Remove subpage “Previous Winners”  - if we do not have information to include here, let’s just remove the page
- [ ] It would be nice to see something on this page letting students know the applications for 2018 will open in late Fall 2017.

**Comment by AntheaLafreniere** [comment]
Content from Karlene:

MD Travel Awards
Each year the CFMS and MD Financial Management set aside funds to provide financial assistance for CFMS member medical students who wish to attend our Annual Meetings.
This initiative supports non-elected members to attend CFMS meetings with the goals of fostering greater member awareness of CFMS structure and function, promoting increased interest in the CFMS and facilitating increased participation in CFMS activities. The application process is competitive and the CFMS routinely receives a far greater number of applications than the number of funded spots available. Applicants are selected based solely on the merits of their written application as judged by a selection committee.
NEW: Travel Awards will be distributed by region to ensure a more equal student representation across the country. There are 8 awards for each meeting, 2 for the Western region, 1 for the Atlantic region, 3 for the Quebec + Ontario regions, and 2 Wildcard awards.

A call for applications will be sent out annually during the following time periods:

CFMS AGM – Insert Month
CFMS Lobby Day - Insert Month
CFMS SGM - Insert Month

Please check back during these time periods for additional application information.

MD Financial Management provides financial products and services, the MD Family of Funds and investment counselling services through the MD Group of Companies. For a detailed list of these companies, visit md.cma.ca

**Comment by pyarmak** [comment]
Can someone let me know what months to fill in for these please:
CFMS AGM – Insert Month
CFMS Lobby Day - Insert Month
CFMS SGM - Insert Month

**Comment by pyarmak** [comment]
Stephen said he got the information and resolved it.
