### ISSUE TITLE
Old - New: Member School Descriptions

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#30]
Descriptions of each member school - [http://www.old.cfms.org/index.php/about/member-schools.html](url)

**Comment by VP-Communications** [comment]
Add following school: Centre de Formation Médicale du Nouveau-Brunswick (French)

**Comment by Threatsignal** [comment]
@VP-Communications Added the descriptions. Please see #75 

Going to require translating for the french descriptions.
Also I still need to style the read more buttons to the websites styles. Other than that it's done.

The new school you mentioned in this issue also can be added to the member-schools.yml file and it will populate on the page dynamically.

**Comment by pyarmak** [comment]
French translation required.

**Comment by Threatsignal** [comment]
see #123
