### ISSUE TITLE
Old - New: History/Timeline, also - update

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#31]
History [http://www.old.cfms.org/index.php/about/more-information/history.html] (url) - Also needs to be updated (ie - Rosemary)

Note: another page could be linked with this one. The Organizational Timeline [http://www.old.cfms.org/index.php/about/more-information/organizational-timeline.html](url)
It would also be really interesting if we could create this timeline into a more interactive one.

**Comment by Threatsignal** [comment]
@VP-Communications
Work for this issue is complete.
See #85 for details on work completed.
Still requires Translating for french pages and possible editing.
