### ISSUE TITLE
Old - New: Position Papers

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#34]
The most recent position papers posted on the new CFMS website [https://www.cfms.org/what-we-do/advocacy/position-papers.html](url) is 2011. 

The position papers on the old CFMS website [http://www.old.cfms.org/index.php/media-and-advocacy-4/positionpapers.html](url) range from 2003 - 2015. 

Need to make decisions about the integration of the old ones to the new, as well as ensuring the old ones reflect the current opinions of medical students.

Perhaps a more interactive / organized way to sort these position papers would be beneficial?  Example - be able to attach tags to them so they can be sorted from the top of that page.

**Comment by sleun090** [comment]
This issue was discussed before and all documents prior to 2010 were removed from the new website.
