### ISSUE TITLE
Website Improvement - Media Release

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#36]
The old CFMS website had a page dedicated to hosting Press Releases [http://www.old.cfms.org/index.php/media-and-advocacy-4/tes.html](url).

With the new website, we could consider having an area under News to incorporate this, because right now there is no central location or way to search for Press Releases specifically.

[https://www.cfms.org/news/](url)

**Comment by Threatsignal** [comment]
See #135
