### ISSUE TITLE
Old - New: Election Toolkit (query - consult GAAC)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#37]
The old website has information about how to vote for the 2015 Canadian Federal Elections [http://www.old.cfms.org/index.php/media-and-advocacy-4/election-toolkit-parent.html](url)

Consider contacting GAAC to update for the new website, or if they want to include or not.

**Comment by VP-Communications** [comment]
@Threatsignal @erm619 I would remove it entirely since there is not currently and election going on. When the next federal election comes around in 2 years we can put one on there then...
