### ISSUE TITLE
Old - New: Student Initiative Grants (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#38]
The old CFMS website has a page dedicated to Student Initiative Grants [http://www.old.cfms.org/index.php/member-benefits-3/funding-opportunities/student-initiative-grant.html](url)

Unsure if these opportunities are still available, so need to confirm if they are relevant. 

This needs to be made more clear on the new CFMS website, instead of being a call for applications.
Also incorporating a form into the website to allow people to apply directly on the website would be ideal.

Also, this may fall best under "What We Do" > "Student Affairs"

**Comment by VP-Communications** [comment]
this still exists. lets create a tab undr what we do --> student affairs --> resources --> Student Inititave Grants

I will contact Alexandra for details. but please use details from old cfms

**Comment by Threatsignal** [comment]
@VP-Communications 
Milestone - Please see #109

**Comment by Threatsignal** [comment]
see #123
