### ISSUE TITLE
SGM Page Updates

### ISSUE THREAD

**Issue by AntheaLafreniere** [cfms-website/cfms-website.github.io#4]
To Do:

1) Post Doctors Manitoba Logo
2) Upload the most recent SGM Agenda

**Comment by pyarmak** [comment]
Where is the logo going and please attach the agenda to this issue (you can drag and drop).
I searched my email and the forwarded chain I have lacks the agenda document attachment.

**Comment by frizzuti** [comment]
Can we please:

1-Change the registration status to CLOSED. as it is currently OPEN 
2- Place on page (under resolutions) that the submission deadline for position papers and motions >$1000 has now passed (pending Carl's okay of course)

Thanks
