### ISSUE TITLE
Old - New: Electives Database (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#40]
The old CFMS website has an Electives Database [http://www.old.cfms.org/index.php/resources-3/carms-interview-database-4.html](http://www.old.cfms.org/index.php/resources-3/carms-interview-database-4.html)

Need to see if this is still relevant since the new portal from AAMC has been introduced. 

Needs to be incorporated to [https://www.cfms.org/resources/](url)

**Comment by pyarmak** [comment]
Is this the project that Aman, Han, and I have been discussing?

**Comment by Threatsignal** [comment]
See #144
