### ISSUE TITLE
Better Integration: CFMS Wellness

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#42]
Currently under the new CFMS website, What we do, student affairs - there is a resource for wellness at [https://www.cfms.org/what-we-do/student-affairs/wellness.html](url).
However, it is linked from outside the website [https://cfmswellness.squarespace.com/](url)

Better incorporation into the new website would be an asset.

**Comment by VP-Communications** [comment]
Leave this for now. I will look into it with Han when she is back.
