### ISSUE TITLE
Old - New: CFMS Communique (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#44]
The old CFMS website has a page dedicated to hosting old versions of the CFMS communique.

Need to determine if want to host them here, or keep them strictly to emails. 

[http://www.old.cfms.org/index.php/resources/publications/rep-communique.html](http://www.old.cfms.org/index.php/resources/publications/rep-communique.html)

It could fit under the new CFMS website at [https://www.cfms.org/resources/](url)

**Comment by VP-Communications** [comment]
See my comment regarding what we do --> under a tab with CFMS communique.

**Comment by Threatsignal** [comment]
See Pull Req #120

**Comment by Threatsignal** [comment]
See #123
