### ISSUE TITLE
Old - New: 12 Stories. Narratives from new canadians (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#47]
One of the old projects on the old CFMS website that could be brought over to the new website is at [http://www.old.cfms.org/index.php/global-health-3/projects/immigrant-and-refugee-health/12-stories-narratives-from-new-canadians.html](url)

Need to discuss with global health if this is something they want brought over or not.

**Comment by VP-Communications** [comment]
leave this out.
