### ISSUE TITLE
Old - New / Query Completion - International Exchanges Database

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#48]
The old CFMS website references a database for international exchanges at [http://www.old.cfms.org/index.php/global-health-3/resources-a-tools.html](url)

Need to check with global health / student affairs if this is complete and if they want it integrated over. 
On the old website it is listed as "coming soon"

**Comment by VP-Communications** [comment]
Leave for now, will revisit with Jess.
