### ISSUE TITLE
Old - New: Photo Gallery of Past Events

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#51]
The Old CFMS website has a page dedicated to photos of the events at [http://www.old.cfms.org/index.php/labs/photo-gallery.html](url)

This should be transitioned over to the new website, in a more organized manner.
I.e. - be able to search pictures by tags (school, event, year, etc.), be able to be sorted into albums, etc.

**Comment by pyarmak** [comment]
Done in 78b1d7d6619e4c9c72c139fd9e40b9cceb5c6e25.
