### ISSUE TITLE
Old - New: Campaigns (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#52]
The old CFMS website has 2 pages:
**Blood Drive information** - [http://www.old.cfms.org/index.php/events-4/campaigns-awareness-philanthropy-and-more/blood-drive.html](url)
**Cancer Fundraiser** - [http://www.old.cfms.org/index.php/events-4/campaigns-awareness-philanthropy-and-more/cancer-fundraiser.html](url)

Need to investigate if these are still running, which executive they fall under, and incorporate them into the new website if they are relevant.

**Comment by VP-Communications** [comment]
we no longer have cancer fundraiser. but we still have blood drives yearly. We can place this tab under student affairs for now.

**Comment by Threatsignal** [comment]
@VP-Communications 
Milestone, see #111

**Comment by Threatsignal** [comment]
See #123
