### ISSUE TITLE
Old - New: Rep Resources (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#53]
Need to determine if the Representative Resources for each school [http://www.old.cfms.org/index.php/cfms-items/rep-resources.html](url) is still relevant, and would be useful to the representatives. 

Would also need to have a unique way to incorporate this information into the new website, if it is relevant. 
Potentially under "Resources" would be the best location.

**Comment by VP-Communications** [comment]
This would be good to have under resources so all students can have access to the updated versions. However it would only become available after student logs in.

**Comment by Threatsignal** [comment]
@VP-Communications 
Milestone, See #112
