### ISSUE TITLE
Old - New: Alumni (query - relevance) 

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#55]
The old CFMS website has a page dedicated to the alumni and what they have done, etc. It's last update was in 2011, so unsure how many new updates there are or if this is worthwhile continuing forward (ie. manpower). However, I believe Rosemary has an excel sheet with the information of alumni.

[http://www.old.cfms.org/index.php/alumini.html](url)

Also unsure where this could be integrated into the new CFMS website, potentially under who we are.

**Comment by VP-Communications** [comment]
I think we should have this under who we are. It could be a side tab.

**Comment by Threatsignal** [comment]
@VP-Communications i just sent a pull request for this issue, When it's accepted you guys should be able to update the page through the user interface.
When you do I may have to add some styles to the page so just post in the issue and mention me.
If you want as well you can just send me a word document or something and i can populate the page myself, either works for me just let me know

**Comment by Threatsignal** [comment]
See #123
