### ISSUE TITLE
Old - New: NomCom (query - relevance)

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#56]
The old CFMS website has a page dedicated to nominations for various committees [http://www.old.cfms.org/index.php/about/more-information/nomcom-par.html](url)

This was last used the Winter of 2016.

This page should be converted over to make it easier for students to find opportunities to get involved with the CFMS and should also include an integrated form to submit applications (instead of using an external google forms).

This could be included under either Who We Are or What We Do.

**Comment by VP-Communications** [comment]
Let's exclude this for now. Deadlines for various committees are always changing. We do have an external google form, but I think it's really easy for all the execs to create versus trying to code something each time.

**Comment by VP-Communications** [comment]
ie. dont worry about this. leave it out
