### ISSUE TITLE
Improvement - Communications Tab under "What We Do"

### ISSUE THREAD

**Issue by VP-Communications** [cfms-website/cfms-website.github.io#60]
I think we should have a communications tab under what we do. 

Side tabs can include:

Communications
Overview
Our Team (Social media and engagement team can go under here)

Resources
- Press Releases
- CFMS in the News (I know this under the news section but we can have it both places)
- Communiques
- Graphics (this can be a place where we put all the graphics we publish)

**Comment by Threatsignal** [comment]
@VP-Communications See #61
Would you like me to build the pages out for this and allow the admins to add the content to the website? or do you have content for some of these pages already?

**Comment by VP-Communications** [comment]
@Threatsignal - I like the first option :) I can write up some content for this on the weekend.

**Comment by Threatsignal** [comment]
@VP-Communications Perfect, I'm currently working on #57. Once I finish that I'll start on this one.

**Comment by Threatsignal** [comment]
@VP-Communications I just finished the issue, see #115. Once the pull request gets reviewed and pulled you will be able to add content through cloudcannon

**Comment by Threatsignal** [comment]
see #123
