### ISSUE TITLE
Improvement - What we do page needs updating

### ISSUE THREAD

**Issue by VP-Communications** [cfms-website/cfms-website.github.io#61]
When you click what we do, there is a list 1, 2, 3 with each of the portfolios except Student Affairs (and potentially communications as well).

We should have one for each so it goes to 1, 2, 3, 4, 5 --> with 4 being student affairs and 5 being communications

**Comment by Threatsignal** [comment]
@VP-Communications 
see #113 
Added student affairs and student-wellness as links to the what-we-do index page.

Issue is at a milestone for now. Still requires two things.
1.) I tried browsing the files of the website but could not find any information regarding communications on the new CFMS website. Is this related to another issue and still needs to be ported over from old cfms website? 

I am referring specifically to
```
We should have one for each so it goes to 1, 2, 3, 4, 5 --> with 4 being student affairs and 5 being communications
```
I just need some clarification on the communications. Where is this content on the website, or if it is from the old website and still needs porting over? Could I please get a link to it.

2.) The whole index page requires a french translation. The page content currently is in English.

Once these two issues are resolved. Please let me know and I will finish the issue.

**Comment by Threatsignal** [comment]
see #123
