### ISSUE TITLE
Update ticket submission guide

### ISSUE THREAD

**Issue by pyarmak** [cfms-website/cfms-website.github.io#71]
Include a "responsible disclosure" section to the issue submission guide (posted on the website) with steps to discuss security concerns in an appropriate manner. Related to #22.

**Comment by erm619** [comment]
[Submitting Ticket for CFMS Website.docx](https://github.com/cfms-website/cfms-website.github.io/files/1259028/Submitting.Ticket.for.CFMS.Website.docx)

[Submitting Ticket for CFMS Website.pdf](https://github.com/cfms-website/cfms-website.github.io/files/1259029/Submitting.Ticket.for.CFMS.Website.pdf)

**Comment by erm619** [comment]
Please note, I do not know how to update the documents on the menu bar. So those have not been updated.

**Comment by pyarmak** [comment]
Thanks for this @erm619. 
I must've overlooked this when you posted it. I have updated the guide on the site.
