### ISSUE TITLE
Add text editing capabilities 

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#8]
The text on the page [https://www.cfms.org/fr/what-we-do/](url) cannot be edited. 
I am looking to add the French translations, but the text editing boxes do not appear. 

Thanks! 
- Evan Mah

**Comment by erm619** [comment]
The text on the page [https://www.cfms.org/fr/new-account.html](url) cannot be edited.

Thanks!
Evan

**Comment by sleun090** [comment]
I've put editing in place for  https://www.cfms.org/fr/what-we-do/ and  https://www.cfms.org/fr/new-account.html.  

There's also a hidden section that needs to be translated:
What is your Authentication Code?

To make sure that you are actually a medical student at one of our member schools, we distribute an authentication code to our membership. You can either find this code: In our CFMS welcome letter, which is in most medical school admissions package.

By contacting the CFMS representatives at your school.
