### ISSUE TITLE
Editing capabilities to Organizational Timeline

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#89]
Is it possible to add editing capabilities to the Organizational Timeline?

Or does everything that needs to be updated need to be sent to IT?

**Comment by Threatsignal** [comment]
@erm619 I had added editing capabilities to the organizational timeline through the organizational-timeline.yml file. These files are available to access through cloudcannon.
I may end up redoing that page as someone found a library that could work very well with the organizational timeline. I should hopefully be able to take a look at it this week. I'm just currently in the middle of doing issue #50. If want, you could post the organizational timeline data here or reach me at jrschellenberg@gmail.com and I would also be happy to update it for you when I get a chance to take a look at it.
