### ISSUE TITLE
Update Menu to French

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#9]
Under [www.cfms.org/Fr/What-we-do/education/](url) the menu needs to be updated to french. The translations are as follows:

**Education - Éducation**
Overview - Aperçu
Our Team - Notre conseil
Educational Advocacy - Plaidoirie scolaire
National Research Chair - Président national de recherche

**Resources - Ressources**
Residency Matchbook - Guide pour le jumelage en résidence
Student Run Clinics Toolkit - Trousse-à-outils pour cliniques dirigées par étudiants
LMCC Preparation Resources - Ressources préparatoires pour LCMC

Thank you,
- Evan M.

**Comment by pyarmak** [comment]
Done.
